name: xpider_chat
description: Professional_ECOMMERCE_APP_Flutter_2024_BACKEND_FIREBASE

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
#---------------------------PACKAGES---------------------------#
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^3.1.2
  google_fonts:
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  contacts_service:
  zego_uikit_prebuilt_call: ^4.16.2
  permission_handler:
  flutter_screenutil:
  uuid: ^4.4.2
  connectivity_plus: ^5.0.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.2
  flutter_native_splash: any

  # ICONS:
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State_Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # FireBase
  firebase_core: ^3.2.0
  table_calendar: ^3.0.0
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.1
  cached_network_image: ^3.3.1


  #---------------------------PACKAGES_END---------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  #---------------------------LOCAL_ASSETS---------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/lottie/
    - assets/images/network/
    - assets/logos/
    - assets/images/animations/
    - assets/images/user/



    #---------------------------FONTS---------------------------#
  fonts:
        - family: Montserrat
          fonts:
            - asset: assets/fonts/Montserrat-Black.ttf
              weight: 300
            - asset: assets/fonts/Montserrat-Regular.ttf
              weight: 300
            - asset: assets/fonts/Montserrat-Medium.ttf
              weight: 400
            - asset: assets/fonts/Montserrat-SemiBold.ttf
              weight: 500

