// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVyBJDxz1wiK8Koqa6uFG1AVpJjhQofg',
    appId: '1:834426903714:web:d940e324c38e9a87740bfb',
    messagingSenderId: '834426903714',
    projectId: 'xpiderchat',
    authDomain: 'xpiderchat.firebaseapp.com',
    storageBucket: 'xpiderchat.appspot.com',
    measurementId: 'G-JQCLM0QR91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTGhlPyFGgvlcUw5qvDCPTVC4XeoC4QA',
    appId: '1:834426903714:android:0046fe6e4bd1cdb5740bfb',
    messagingSenderId: '834426903714',
    projectId: 'xpiderchat',
    storageBucket: 'xpiderchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dytVrTFb8uSHMlqQr8A7Lwssbgq4ZEo',
    appId: '1:834426903714:ios:f886b2b13243ad44740bfb',
    messagingSenderId: '834426903714',
    projectId: 'xpiderchat',
    storageBucket: 'xpiderchat.appspot.com',
    androidClientId: '834426903714-pg5fdil1b392clnasu45e1uirasdfcbv.apps.googleusercontent.com',
    iosClientId: '834426903714-e43gdcn422qucjo6vb3e2k20qur95boh.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpiderChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dytVrTFb8uSHMlqQr8A7Lwssbgq4ZEo',
    appId: '1:834426903714:ios:f886b2b13243ad44740bfb',
    messagingSenderId: '834426903714',
    projectId: 'xpiderchat',
    storageBucket: 'xpiderchat.appspot.com',
    androidClientId: '834426903714-pg5fdil1b392clnasu45e1uirasdfcbv.apps.googleusercontent.com',
    iosClientId: '834426903714-e43gdcn422qucjo6vb3e2k20qur95boh.apps.googleusercontent.com',
    iosBundleId: 'com.example.xpiderChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNVyBJDxz1wiK8Koqa6uFG1AVpJjhQofg',
    appId: '1:834426903714:web:787619125f95e8b9740bfb',
    messagingSenderId: '834426903714',
    projectId: 'xpiderchat',
    authDomain: 'xpiderchat.firebaseapp.com',
    storageBucket: 'xpiderchat.appspot.com',
    measurementId: 'G-S9Y9QY1HP0',
  );

}